# Generated by Django 3.1.5 on 2021-02-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('age', models.CharField(choices=[('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+'), ('all', 'all')], max_length=4)),
                ('IMDb_rating', models.FloatField()),
                ('Rotten_Tomatoes_rating', models.CharField(max_length=3)),
                ('netflix', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('hulu', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('prime', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('disney', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('directors', models.CharField(help_text='Separate each director with commas', max_length=50)),
                ('genres', models.CharField(help_text='Separate each genre with commas', max_length=50)),
                ('country', models.CharField(help_text='Separate each country with commas', max_length=50)),
                ('language', models.CharField(help_text='Separate each language with commas', max_length=50)),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
