# Generated by Django 3.1.5 on 2021-03-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieuniverse', '0003_auto_20210301_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rotten_Tomatoes_rating',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.TextField(choices=[('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+'), ('all', 'all')], max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.TextField(help_text='Separate each country with commas', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.TextField(help_text='Separate each director with commas', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(help_text='Separate each genre with commas', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.TextField(help_text='Separate each language with commas', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.TextField(max_length=4),
        ),
    ]
