# Generated by Django 3.1.5 on 2021-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieuniverse', '0004_auto_20210301_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rotten_Tomatoes_rating',
            field=models.IntegerField(max_length=3),
        ),
    ]
