# Generated by Django 3.1.5 on 2021-03-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieuniverse', '0008_auto_20210303_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('year', models.TextField(max_length=4)),
                ('age', models.TextField(choices=[('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+'), ('all', 'all')], max_length=4)),
                ('IMDb_rating', models.FloatField()),
                ('Rotten_Tomatoes_rating', models.IntegerField()),
                ('netflix', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('hulu', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('prime', models.IntegerField(help_text='1 for available, 0 for not available')),
                ('disney', models.IntegerField(help_text='1 for available, 0 for not available')),
            ],
        ),
    ]
